import type { Metadata } from "next";
import { Geist, Geist_Mono , Dosis } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/navbar";
import Footer from "@/components/common/footer";
import { Toaster } from "sonner";
import AuthProvider from "@/providers/authProvider";
import CartDataProvider from "@/providers/cartDataProvider";

const DosisSans = Dosis({
  variable: "--font-Dosis-sans",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//${geistSans.variable} ${geistMono.variable}

export const metadata: Metadata = {
  title: "GOCART",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DosisSans.className} antialiased`} >
       <AuthProvider>
         <CartDataProvider>
          <Navbar />
           <main className="min-h-[calc(100vh-240px)]">
            {children}
            <Toaster richColors position="top-right"/>
            </main>
            <Footer/>
         </CartDataProvider>
       </AuthProvider>
      </body>
    </html>
  );
}
